<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joe Wilder, Justin Perkins">
<meta name="dcterms.date" content="2023-12-13">

<title>Heart Disease Key Indicators</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Analysis_files/libs/quarto-html/quarto.js"></script>
<script src="Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Analysis_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">

<script src="Analysis_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Analysis_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background-of-data-set" id="toc-background-of-data-set" class="nav-link active" data-scroll-target="#background-of-data-set">Background of Data Set</a></li>
  <li><a href="#statement-of-reason" id="toc-statement-of-reason" class="nav-link" data-scroll-target="#statement-of-reason">Statement of Reason</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-dictionary" id="toc-data-dictionary" class="nav-link" data-scroll-target="#data-dictionary">Data Dictionary</a></li>
  <li><a href="#data-preview" id="toc-data-preview" class="nav-link" data-scroll-target="#data-preview">Data Preview</a></li>
  <li><a href="#target-variable-distribution" id="toc-target-variable-distribution" class="nav-link" data-scroll-target="#target-variable-distribution">Target Variable Distribution</a></li>
  <li><a href="#predictor-variable-distributions" id="toc-predictor-variable-distributions" class="nav-link" data-scroll-target="#predictor-variable-distributions">Predictor Variable Distributions</a></li>
  <li><a href="#kurtosis-for-numeric-columns" id="toc-kurtosis-for-numeric-columns" class="nav-link" data-scroll-target="#kurtosis-for-numeric-columns">Kurtosis For Numeric columns</a></li>
  </ul></li>
  <li><a href="#statistical-modeling" id="toc-statistical-modeling" class="nav-link" data-scroll-target="#statistical-modeling">Statistical Modeling</a>
  <ul class="collapse">
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing">Data Pre-processing</a></li>
  <li><a href="#base-model-construction" id="toc-base-model-construction" class="nav-link" data-scroll-target="#base-model-construction">Base Model Construction</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Heart Disease Key Indicators</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joe Wilder, Justin Perkins </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 13, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="background-of-data-set" class="level2">
<h2 class="anchored" data-anchor-id="background-of-data-set">Background of Data Set</h2>
<p>In this report, the primary data set is derived from the CDC’s BRFSS Survey, which has been thoughtfully queried and enhanced for user-friendliness by Kaggle contributor <a href="https://www.kaggle.com/kamilpytlak">Kamil Pytlak</a>. The modifications made include the removal of irreverent columns, and streamlining the data set for more focused and accessible analysis.</p>
<p>The BRFSS Survery according to the CDC is</p>
<blockquote class="blockquote">
<p>[…] the nation’s premier system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world.</p>
</blockquote>
</section>
<section id="statement-of-reason" class="level2">
<h2 class="anchored" data-anchor-id="statement-of-reason">Statement of Reason</h2>
<p>By the end of our analysis, we hope to be able to accurately predict whether or not a patient did or did not have a heart attack. In addition, we hope to be able to identify some of the key features used in our predictions. With this information, medical professionals will be able to gauge better the risk a patient is at for having a heart attack based on a list of indicators. Or, they can input all the patient’s information, and get a prediction from the trained model.</p>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">State</td>
<td style="text-align: left;">State FIPS Code</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex</td>
<td style="text-align: left;">Sex of Respondent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GeneralHealth</td>
<td style="text-align: left;">Would you say that in general your health is:</td>
</tr>
<tr class="even">
<td style="text-align: left;">PhysicalHealthDays</td>
<td style="text-align: left;">Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MentalHealthDays</td>
<td style="text-align: left;">Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?</td>
</tr>
<tr class="even">
<td style="text-align: left;">LastCheckupTime</td>
<td style="text-align: left;">About how long has it been since you last visited a doctor for a routine checkup?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PhysicalActivities</td>
<td style="text-align: left;">During the past month, other than your regular job, did you participate in any physical activities or exercises such as running, calisthenics, golf, gardening, or walking for exercise?</td>
</tr>
<tr class="even">
<td style="text-align: left;">SleepHours</td>
<td style="text-align: left;">On average, how many hours of sleep do you get in a 24-hour period?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RemovedTeeth</td>
<td style="text-align: left;">Not including teeth lost for injury or orthodontics, how many of your permanent teeth have been removed because of tooth decay or gum disease?</td>
</tr>
<tr class="even">
<td style="text-align: left;">HadHeartAttack</td>
<td style="text-align: left;">(Ever told) you had a heart attack, also called a myocardial infarction?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HadAngina</td>
<td style="text-align: left;">(Ever told) (you had) angina or coronary heart disease?</td>
</tr>
<tr class="even">
<td style="text-align: left;">HadStroke</td>
<td style="text-align: left;">(Ever told) (you had) a stroke.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HadAsthma</td>
<td style="text-align: left;">(Ever told) (you had) asthma?</td>
</tr>
<tr class="even">
<td style="text-align: left;">HadSkinCancer</td>
<td style="text-align: left;">(Ever told) (you had) skin cancer that is not melanoma?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HadCOPD</td>
<td style="text-align: left;">(Ever told) (you had) C.O.P.D. (chronic obstructive pulmonary disease), emphysema or chronic bronchitis?</td>
</tr>
<tr class="even">
<td style="text-align: left;">HadDepressiveDisorder</td>
<td style="text-align: left;">(Ever told) (you had) a depressive disorder (including depression, major depression, dysthymia, or minor depression)?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HadKidneyDisease</td>
<td style="text-align: left;">Not including kidney stones, bladder infection or incontinence, were you ever told you had kidney disease?</td>
</tr>
<tr class="even">
<td style="text-align: left;">HadArthritis</td>
<td style="text-align: left;">(Ever told) (you had) some form of arthritis, rheumatoid arthritis, gout, lupus, or fibromyalgia? (Arthritis diagnoses include: rheumatism, polymyalgia rheumatica; osteoarthritis (not osteporosis); tendonitis, bursitis, bunion, tennis elbow; carpal tunnel syndrome, tarsal tunnel syndrome; joint infection, etc.)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HadDiabetes</td>
<td style="text-align: left;">(Ever told) (you had) diabetes?</td>
</tr>
<tr class="even">
<td style="text-align: left;">DeafOrHardOfHearing</td>
<td style="text-align: left;">Are you deaf or do you have serious difficulty hearing?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BlindOrVisionDifficulty</td>
<td style="text-align: left;">Are you blind or do you have serious difficulty seeing, even when wearing glasses?</td>
</tr>
<tr class="even">
<td style="text-align: left;">DifficultyConcentrating</td>
<td style="text-align: left;">Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DifficultyWalking</td>
<td style="text-align: left;">Do you have serious difficulty walking or climbing stairs?</td>
</tr>
<tr class="even">
<td style="text-align: left;">DifficultyDressingBathing</td>
<td style="text-align: left;">Do you have difficulty dressing or bathing?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DifficultyErrands</td>
<td style="text-align: left;">Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting a doctor´s office or shopping?</td>
</tr>
<tr class="even">
<td style="text-align: left;">SmokerStatus</td>
<td style="text-align: left;">Four-level smoker status: Everyday smoker, Someday smoker, Former smoker, Non-smoker</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ECigaretteUsage</td>
<td style="text-align: left;">Would you say you have never used e-cigarettes or other electronic vaping products in your entire life or now use them every day, use them some days, or used them in the past but do not currently use them at all?</td>
</tr>
<tr class="even">
<td style="text-align: left;">ChestScan</td>
<td style="text-align: left;">Have you ever had a CT or CAT scan of your chest area?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceEthnicityCategory</td>
<td style="text-align: left;">Five-level race/ethnicity category</td>
</tr>
<tr class="even">
<td style="text-align: left;">AgeCategory</td>
<td style="text-align: left;">Fourteen-level age category</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HeightInMeters</td>
<td style="text-align: left;">Reported height in meters</td>
</tr>
<tr class="even">
<td style="text-align: left;">WeightInKilograms</td>
<td style="text-align: left;">Reported weight in kilograms</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">Body Mass Index (BMI)</td>
</tr>
<tr class="even">
<td style="text-align: left;">AlcoholDrinkers</td>
<td style="text-align: left;">Adults who reported having had at least one drink of alcohol in the past 30 days.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HIVTesting</td>
<td style="text-align: left;">Adults who have ever been tested for HIV</td>
</tr>
<tr class="even">
<td style="text-align: left;">FluVaxLast12</td>
<td style="text-align: left;">During the past 12 months, have you had either flu vaccine that was sprayed in your nose or flu shot injected into your arm?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PneumoVaxEver</td>
<td style="text-align: left;">Have you ever had a pneumonia shot also known as a pneumococcal vaccine?</td>
</tr>
<tr class="even">
<td style="text-align: left;">TetanusLast10Tdap</td>
<td style="text-align: left;">Have you received a tetanus shot in the past 10 years? Was this Tdap, the tetanus shot that also has pertussis or whooping cough vaccine?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HighRiskLastYear</td>
<td style="text-align: left;">You have injected any drug other than those prescribed for you in the past year. You have been treated for a sexually transmitted disease or STD in the past year. You have given or received money or drugs in exchange for sex in the past year.</td>
</tr>
<tr class="even">
<td style="text-align: left;">CovidPos</td>
<td style="text-align: left;">Has a doctor, nurse, or other health professional ever told you that you tested positive for COVID 19?</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
</section>
<section id="data-preview" class="level3">
<h3 class="anchored" data-anchor-id="data-preview">Data Preview</h3>
<p>Here is a preview of the data set that we are using for our analysis. Each row corresponds to a single respondent, and each column corresponds to a question on the CDC’s BRFSS Survey. The intersections of each row and column indicate how the respondent answered the corresponding question.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">State</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">GeneralHealth</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">PhysicalHealthDays</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">MentalHealthDays</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">LastCheckupTime</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">PhysicalActivities</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SleepHours</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">RemovedTeeth</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadHeartAttack</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadAngina</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadStroke</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadAsthma</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadSkinCancer</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadCOPD</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadDepressiveDisorder</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadKidneyDisease</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadArthritis</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HadDiabetes</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DeafOrHardOfHearing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">BlindOrVisionDifficulty</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DifficultyConcentrating</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DifficultyWalking</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DifficultyDressingBathing</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">DifficultyErrands</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">SmokerStatus</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ECigaretteUsage</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ChestScan</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">RaceEthnicityCategory</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">AgeCategory</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">HeightInMeters</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">WeightInKilograms</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BMI</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">AlcoholDrinkers</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HIVTesting</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">FluVaxLast12</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">PneumoVaxEver</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">TetanusLast10Tdap</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">HighRiskLastYear</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">CovidPos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Very good</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Within past year (anytime less than 12 months ago)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">None of them</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">Never used e-cigarettes in my entire life</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">White only, Non-Hispanic</td>
<td style="text-align: left;">Age 65 to 69</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: right;">71.67</td>
<td style="text-align: right;">27.99</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes, received Tdap</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Very good</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Within past year (anytime less than 12 months ago)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">None of them</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">Never used e-cigarettes in my entire life</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">White only, Non-Hispanic</td>
<td style="text-align: left;">Age 70 to 74</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">95.25</td>
<td style="text-align: right;">30.13</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes, received tetanus shot but not sure what type</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Very good</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Within past year (anytime less than 12 months ago)</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">6 or more, but not all</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Former smoker</td>
<td style="text-align: left;">Never used e-cigarettes in my entire life</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">White only, Non-Hispanic</td>
<td style="text-align: left;">Age 75 to 79</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">108.86</td>
<td style="text-align: right;">31.66</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No, did not receive any tetanus shot in the past 10 years</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
</section>
<section id="target-variable-distribution" class="level3">
<h3 class="anchored" data-anchor-id="target-variable-distribution">Target Variable Distribution</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Analysis_files/figure-html/Target%20Variable%20Distribution-1.png" class="img-fluid" width="614"></p>
</div>
</div>
<hr>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Count</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Percentage of Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">232587</td>
<td style="text-align: left;">94.54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">13435</td>
<td style="text-align: left;">5.46%</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>As shown above, there is not an even distribution of respondents who have or have not had a heart attack. Only 5.46% of people responded saying that they have had a heart attack in the past.</p>
<hr>
</section>
<section id="predictor-variable-distributions" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variable-distributions">Predictor Variable Distributions</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Analysis_files/figure-html/State%20Distribution-1.png" class="img-fluid" width="1920"></p>
</div>
</div>
<p>In our data set, there are a few larger clusters of respondents when looking state by state. The state with the most responses was Washington state with a total of 15000.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Analysis_files/figure-html/General%20Health%20Distribution-3.png" class="img-fluid" width="614"></p>
</div>
</div>
<p>When looking at the respondents’ self-reported view of their overall health, the data more or less follows a normal distribution with a left-skew. The most common response to the question was to rate their overall health as “Very Good”.</p>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Analysis_files/figure-html/BMI%20Distribution-5.png" class="img-fluid" width="614"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Analysis_files/figure-html/BMI%20Distribution-6.png" class="img-fluid" width="614"></p>
</div>
</div>
</div>
<p>BMI, body mass index, is the summary of the relationship between a person’s height and weight. It can often be an indicator of poor health and we wanted to explore its relationship with having a heart attack. When looking at the histogram, you might think that BMI has a bimodal distribution. However, the density graph shows us that it is more of a left-skewed normal distribution.</p>
<p>Respondents who reported not having a heart attack had an average BMI of 28.62, while those who reported having a heart attack had an average of 29.49. That being a difference of -0.87.</p>
</section>
<section id="kurtosis-for-numeric-columns" class="level3">
<h3 class="anchored" data-anchor-id="kurtosis-for-numeric-columns">Kurtosis For Numeric columns</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PhysicalHealthDays</td>
<td style="text-align: right;">3.9728649</td>
</tr>
<tr class="even">
<td style="text-align: left;">MentalHealthDays</td>
<td style="text-align: right;">3.8587287</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SleepHours</td>
<td style="text-align: right;">7.2068297</td>
</tr>
<tr class="even">
<td style="text-align: left;">HeightInMeters</td>
<td style="text-align: right;">0.0073723</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WeightInKilograms</td>
<td style="text-align: right;">2.3372781</td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: right;">3.8980498</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Kurtosis is a measure of the “tailedness” of a probability distribution. It quantifies how much a distribution deviates from a normal distribution in terms of the concentration of data in its tails. There are three main types of kurtosis:</p>
<ol type="1">
<li><p><strong>Mesokurtic (Kurtosis = 0):</strong> The distribution has a shape similar to a normal distribution. The tails are neither too heavy nor too light.</p></li>
<li><p><strong>Leptokurtic (Positive Kurtosis):</strong> The distribution has fatter tails and a sharper peak than a normal distribution. This indicates that there are more extreme values in the distribution, and it may have more outliers.</p></li>
<li><p><strong>Platykurtic (Negative Kurtosis):</strong> The distribution has lighter tails and a flatter peak than a normal distribution. This suggests that there are fewer extreme values, and the distribution has fewer outliers.</p></li>
</ol>
<p>In our data, most of our features are leptokurtic with some scores in excess of 7. This means most of our numeric features have one or two values that appear significantly more than any other with large tails that dissipate slowly. The only feature that resembles a normal distribution is Height In Meters with a Kurtosis score of 0.0073723.</p>
<hr>
</section>
</section>
<section id="statistical-modeling" class="level2">
<h2 class="anchored" data-anchor-id="statistical-modeling">Statistical Modeling</h2>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
<p>A lot of our columns are represented with yes and no values. To avoid processing these columns as categorical variables, we can convert them to numerical by having 0 represent no, and 1 represent yes. This will be easier to understand for our model.</p>
</section>
<section id="data-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-pre-processing">Data Pre-processing</h3>
<p>To prepare our model for training, we need to split our data into train and test splits. The training data will be used for model construction and the test data will be used to evaluate our models.</p>
<p>We also use stratification when we create our train test splits. While we do have a lot of data in our data set, the majority of the data is for patients who have not had heart disease. By stratifying for the HadHeartAttack column, we ensure our model has plenty of data examples from patients who do have heart disease. This allows our model to better differentiate which patients have heart disease and which ones do not.</p>
<p>When building a model, we need to classify our columns as either numerical or categorical. This is because we process the data differently based on that. In our modeling pipeline, numerical variables need to be scaled, and for categorical columns, we need to use one hot encoding. Scaling is done to make it easier for our model to make distinctions between small distances. One hot encoding is done to map our categorical variables to numerical columns that our model can understand.</p>
<section id="numerical-columns" class="level4">
<h4 class="anchored" data-anchor-id="numerical-columns">Numerical Columns</h4>
<ul>
<li>GeneralHealth</li>
<li>PhysicalHealthDays</li>
<li>MentalHealthDays</li>
<li>PhysicalActivities</li>
<li>SleepHours</li>
<li>HadAngina</li>
<li>HadStroke</li>
<li>HadAsthma</li>
<li>HadSkinCancer</li>
<li>HadCOPD</li>
<li>HadDepressiveDisorder</li>
<li>HadKidneyDisease</li>
<li>HadArthritis</li>
<li>DeafOrHardOfHearing</li>
<li>BlindOrVisionDifficulty</li>
<li>DifficultyConcentrating</li>
<li>DifficultyWalking</li>
<li>DifficultyDressingBathing</li>
<li>DifficultyErrands</li>
<li>ChestScan</li>
<li>HeightInMeters</li>
<li>WeightInKilograms</li>
<li>BMI</li>
<li>AlcoholDrinkers</li>
<li>HIVTesting</li>
<li>FluVaxLast12</li>
<li>PneumoVaxEver</li>
<li>HighRiskLastYear</li>
</ul>
</section>
<section id="categorical-columns" class="level4">
<h4 class="anchored" data-anchor-id="categorical-columns">Categorical Columns</h4>
<ul>
<li>State</li>
<li>Sex</li>
<li>LastCheckupTime</li>
<li>RemovedTeeth</li>
<li>HadDiabetes</li>
<li>SmokerStatus</li>
<li>ECigaretteUsage</li>
<li>RaceEthnicityCategory</li>
<li>AgeCategory</li>
<li>TetanusLast10Tdap</li>
<li>CovidPos</li>
</ul>
</section>
</section>
<section id="base-model-construction" class="level3">
<h3 class="anchored" data-anchor-id="base-model-construction">Base Model Construction</h3>
<p>There are many different models that we could use to make predictions on our data set. To figure out which model we should use, we will build baseline models with minimal training and make predictions on our data set. This will allow us to quantify which model we should use for our final predictions.</p>
<p>The models we have chosen to test are the logistic regression model, the random forest classifier, the decision tree classifier, and the linear discriminant analysis model. All of these models can be used to make predictions that classify if a patient has heart disease or not. It is also important to do some basic parameter training on our models to help us identify which model might perform best. Each model has a unique parameter grid that we will train over.</p>
<p>Once we have our parameter grids, we can feed them into a random search. The random search function is what will train our model. It allows us to go through and train many different models using the different combinations of parameters we have defined in our parameter grids. The output we get is the best parameter combination that was found in the training session for each model we have defined.</p>
<div class="cell">
<div class="cell-output-display">
<style>#sk-container-id-1 {color: black;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num_cols',
                                                                               Pipeline(steps=[('num_imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('norm',
                                                                                                StandardScaler())]),
                                                                               ['GeneralHealth',
                                                                                'PhysicalHealthDays',
                                                                                'MentalHealthDays',
                                                                                'PhysicalActivities',
                                                                                'SleepHours',
                                                                                'HadAngina',
                                                                                'HadStroke',
                                                                                'HadAsthma',
                                                                                'HadSkinCancer',
                                                                                'Had...
                                                                                'Sex',
                                                                                'LastCheckupTime',
                                                                                'RemovedTeeth',
                                                                                'HadDiabetes',
                                                                                'SmokerStatus',
                                                                                'ECigaretteUsage',
                                                                                'RaceEthnicityCategory',
                                                                                'AgeCategory',
                                                                                'TetanusLast10Tdap',
                                                                                'CovidPos'])])),
                                             ('model',
                                              LinearDiscriminantAnalysis())]),
                   n_iter=1, n_jobs=-1,
                   param_distributions={'model__priors': [None, [0.2, 0.8],
                                                          [0.5, 0.5]],
                                        'model__tol': [0.0001, 0.001, 0.01]},
                   random_state=42, scoring='accuracy')</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox"><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">RandomizedSearchCV</label><div class="sk-toggleable__content"><pre>RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num_cols',
                                                                               Pipeline(steps=[('num_imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('norm',
                                                                                                StandardScaler())]),
                                                                               ['GeneralHealth',
                                                                                'PhysicalHealthDays',
                                                                                'MentalHealthDays',
                                                                                'PhysicalActivities',
                                                                                'SleepHours',
                                                                                'HadAngina',
                                                                                'HadStroke',
                                                                                'HadAsthma',
                                                                                'HadSkinCancer',
                                                                                'Had...
                                                                                'Sex',
                                                                                'LastCheckupTime',
                                                                                'RemovedTeeth',
                                                                                'HadDiabetes',
                                                                                'SmokerStatus',
                                                                                'ECigaretteUsage',
                                                                                'RaceEthnicityCategory',
                                                                                'AgeCategory',
                                                                                'TetanusLast10Tdap',
                                                                                'CovidPos'])])),
                                             ('model',
                                              LinearDiscriminantAnalysis())]),
                   n_iter=1, n_jobs=-1,
                   param_distributions={'model__priors': [None, [0.2, 0.8],
                                                          [0.5, 0.5]],
                                        'model__tol': [0.0001, 0.001, 0.01]},
                   random_state=42, scoring='accuracy')</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox"><label for="sk-estimator-id-2" class="sk-toggleable__label sk-toggleable__label-arrow">estimator: Pipeline</label><div class="sk-toggleable__content"><pre>Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_cols',
                                                  Pipeline(steps=[('num_imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('norm',
                                                                   StandardScaler())]),
                                                  ['GeneralHealth',
                                                   'PhysicalHealthDays',
                                                   'MentalHealthDays',
                                                   'PhysicalActivities',
                                                   'SleepHours', 'HadAngina',
                                                   'HadStroke', 'HadAsthma',
                                                   'HadSkinCancer', 'HadCOPD',
                                                   'HadDepressiveDisorder',
                                                   'Had...
                                                   'HighRiskLastYear']),
                                                 ('cat_cols',
                                                  Pipeline(steps=[('cat_imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['State', 'Sex',
                                                   'LastCheckupTime',
                                                   'RemovedTeeth',
                                                   'HadDiabetes',
                                                   'SmokerStatus',
                                                   'ECigaretteUsage',
                                                   'RaceEthnicityCategory',
                                                   'AgeCategory',
                                                   'TetanusLast10Tdap',
                                                   'CovidPos'])])),
                ('model', LinearDiscriminantAnalysis())])</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-3" type="checkbox"><label for="sk-estimator-id-3" class="sk-toggleable__label sk-toggleable__label-arrow">preprocessor: ColumnTransformer</label><div class="sk-toggleable__content"><pre>ColumnTransformer(transformers=[('num_cols',
                                 Pipeline(steps=[('num_imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('norm', StandardScaler())]),
                                 ['GeneralHealth', 'PhysicalHealthDays',
                                  'MentalHealthDays', 'PhysicalActivities',
                                  'SleepHours', 'HadAngina', 'HadStroke',
                                  'HadAsthma', 'HadSkinCancer', 'HadCOPD',
                                  'HadDepressiveDisorder', 'HadKidneyDisease',
                                  'HadArthritis', 'D...
                                  'FluVaxLast12', 'PneumoVaxEver',
                                  'HighRiskLastYear']),
                                ('cat_cols',
                                 Pipeline(steps=[('cat_imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('one-hot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['State', 'Sex', 'LastCheckupTime',
                                  'RemovedTeeth', 'HadDiabetes', 'SmokerStatus',
                                  'ECigaretteUsage', 'RaceEthnicityCategory',
                                  'AgeCategory', 'TetanusLast10Tdap',
                                  'CovidPos'])])</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-4" type="checkbox"><label for="sk-estimator-id-4" class="sk-toggleable__label sk-toggleable__label-arrow">num_cols</label><div class="sk-toggleable__content"><pre>['GeneralHealth', 'PhysicalHealthDays', 'MentalHealthDays', 'PhysicalActivities', 'SleepHours', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands', 'ChestScan', 'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'HighRiskLastYear']</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-5" type="checkbox"><label for="sk-estimator-id-5" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='median')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-6" type="checkbox"><label for="sk-estimator-id-6" class="sk-toggleable__label sk-toggleable__label-arrow">StandardScaler</label><div class="sk-toggleable__content"><pre>StandardScaler()</pre></div></div></div></div></div></div></div></div><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-7" type="checkbox"><label for="sk-estimator-id-7" class="sk-toggleable__label sk-toggleable__label-arrow">cat_cols</label><div class="sk-toggleable__content"><pre>['State', 'Sex', 'LastCheckupTime', 'RemovedTeeth', 'HadDiabetes', 'SmokerStatus', 'ECigaretteUsage', 'RaceEthnicityCategory', 'AgeCategory', 'TetanusLast10Tdap', 'CovidPos']</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-8" type="checkbox"><label for="sk-estimator-id-8" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='most_frequent')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-9" type="checkbox"><label for="sk-estimator-id-9" class="sk-toggleable__label sk-toggleable__label-arrow">OneHotEncoder</label><div class="sk-toggleable__content"><pre>OneHotEncoder(handle_unknown='ignore')</pre></div></div></div></div></div></div></div></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-10" type="checkbox"><label for="sk-estimator-id-10" class="sk-toggleable__label sk-toggleable__label-arrow">LinearDiscriminantAnalysis</label><div class="sk-toggleable__content"><pre>LinearDiscriminantAnalysis()</pre></div></div></div></div></div></div></div></div></div></div></div></div>
</div>
</div>
<p>Here we will now make predictions on our baseline models and decide which one we should train further. We chose to use accuracy as a prediction metric because our model is only predicting a boolean value. Because of this, we do not need anything more complicated than accuracy.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy for LogisticRegression: 0.9482967463156953
Accuracy for RandomForestClassifier: 0.9456142159146094
Accuracy for DecisionTreeClassifier: 0.945410963882089
Accuracy for LinearDiscriminantAnalysis: 0.932241025031136</code></pre>
</div>
</div>
<p>After trying all the models, it seems the Logistic Regression model has the best accuracy. Let’s stick with that one and try to improve it.</p>
<p>We do this by increasing the number of iterations we train on and going over more params</p>
<div class="cell">
<div class="cell-output-display">
<style>#sk-container-id-2 {color: black;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-2" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num_cols',
                                                                               Pipeline(steps=[('num_imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('norm',
                                                                                                StandardScaler())]),
                                                                               ['GeneralHealth',
                                                                                'PhysicalHealthDays',
                                                                                'MentalHealthDays',
                                                                                'PhysicalActivities',
                                                                                'SleepHours',
                                                                                'HadAngina',
                                                                                'HadStroke',
                                                                                'HadAsthma',
                                                                                'HadSkinCancer',
                                                                                'Had...
                   param_distributions={'model__C': [0.001, 0.01, 0.1, 1, 10,
                                                     100],
                                        'model__class_weight': [None,
                                                                'balanced'],
                                        'model__fit_intercept': [True],
                                        'model__intercept_scaling': [1, 2, 3],
                                        'model__max_iter': [948, 806, 985, 865,
                                                            681, 887, 185, 139,
                                                            329, 122],
                                        'model__multi_class': ['ovr'],
                                        'model__penalty': ['l2'],
                                        'model__solver': ['lbfgs', 'sag',
                                                          'saga'],
                                        'model__tol': [0.0001]},
                   random_state=42, scoring='accuracy')</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-11" type="checkbox"><label for="sk-estimator-id-11" class="sk-toggleable__label sk-toggleable__label-arrow">RandomizedSearchCV</label><div class="sk-toggleable__content"><pre>RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num_cols',
                                                                               Pipeline(steps=[('num_imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('norm',
                                                                                                StandardScaler())]),
                                                                               ['GeneralHealth',
                                                                                'PhysicalHealthDays',
                                                                                'MentalHealthDays',
                                                                                'PhysicalActivities',
                                                                                'SleepHours',
                                                                                'HadAngina',
                                                                                'HadStroke',
                                                                                'HadAsthma',
                                                                                'HadSkinCancer',
                                                                                'Had...
                   param_distributions={'model__C': [0.001, 0.01, 0.1, 1, 10,
                                                     100],
                                        'model__class_weight': [None,
                                                                'balanced'],
                                        'model__fit_intercept': [True],
                                        'model__intercept_scaling': [1, 2, 3],
                                        'model__max_iter': [948, 806, 985, 865,
                                                            681, 887, 185, 139,
                                                            329, 122],
                                        'model__multi_class': ['ovr'],
                                        'model__penalty': ['l2'],
                                        'model__solver': ['lbfgs', 'sag',
                                                          'saga'],
                                        'model__tol': [0.0001]},
                   random_state=42, scoring='accuracy')</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-12" type="checkbox"><label for="sk-estimator-id-12" class="sk-toggleable__label sk-toggleable__label-arrow">estimator: Pipeline</label><div class="sk-toggleable__content"><pre>Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_cols',
                                                  Pipeline(steps=[('num_imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('norm',
                                                                   StandardScaler())]),
                                                  ['GeneralHealth',
                                                   'PhysicalHealthDays',
                                                   'MentalHealthDays',
                                                   'PhysicalActivities',
                                                   'SleepHours', 'HadAngina',
                                                   'HadStroke', 'HadAsthma',
                                                   'HadSkinCancer', 'HadCOPD',
                                                   'HadDepressiveDisorder',
                                                   'Had...
                                                   'HighRiskLastYear']),
                                                 ('cat_cols',
                                                  Pipeline(steps=[('cat_imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['State', 'Sex',
                                                   'LastCheckupTime',
                                                   'RemovedTeeth',
                                                   'HadDiabetes',
                                                   'SmokerStatus',
                                                   'ECigaretteUsage',
                                                   'RaceEthnicityCategory',
                                                   'AgeCategory',
                                                   'TetanusLast10Tdap',
                                                   'CovidPos'])])),
                ('model', LogisticRegression())])</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-13" type="checkbox"><label for="sk-estimator-id-13" class="sk-toggleable__label sk-toggleable__label-arrow">preprocessor: ColumnTransformer</label><div class="sk-toggleable__content"><pre>ColumnTransformer(transformers=[('num_cols',
                                 Pipeline(steps=[('num_imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('norm', StandardScaler())]),
                                 ['GeneralHealth', 'PhysicalHealthDays',
                                  'MentalHealthDays', 'PhysicalActivities',
                                  'SleepHours', 'HadAngina', 'HadStroke',
                                  'HadAsthma', 'HadSkinCancer', 'HadCOPD',
                                  'HadDepressiveDisorder', 'HadKidneyDisease',
                                  'HadArthritis', 'D...
                                  'FluVaxLast12', 'PneumoVaxEver',
                                  'HighRiskLastYear']),
                                ('cat_cols',
                                 Pipeline(steps=[('cat_imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('one-hot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['State', 'Sex', 'LastCheckupTime',
                                  'RemovedTeeth', 'HadDiabetes', 'SmokerStatus',
                                  'ECigaretteUsage', 'RaceEthnicityCategory',
                                  'AgeCategory', 'TetanusLast10Tdap',
                                  'CovidPos'])])</pre></div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-14" type="checkbox"><label for="sk-estimator-id-14" class="sk-toggleable__label sk-toggleable__label-arrow">num_cols</label><div class="sk-toggleable__content"><pre>['GeneralHealth', 'PhysicalHealthDays', 'MentalHealthDays', 'PhysicalActivities', 'SleepHours', 'HadAngina', 'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty', 'DifficultyConcentrating', 'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands', 'ChestScan', 'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'HighRiskLastYear']</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-15" type="checkbox"><label for="sk-estimator-id-15" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='median')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-16" type="checkbox"><label for="sk-estimator-id-16" class="sk-toggleable__label sk-toggleable__label-arrow">StandardScaler</label><div class="sk-toggleable__content"><pre>StandardScaler()</pre></div></div></div></div></div></div></div></div><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-17" type="checkbox"><label for="sk-estimator-id-17" class="sk-toggleable__label sk-toggleable__label-arrow">cat_cols</label><div class="sk-toggleable__content"><pre>['State', 'Sex', 'LastCheckupTime', 'RemovedTeeth', 'HadDiabetes', 'SmokerStatus', 'ECigaretteUsage', 'RaceEthnicityCategory', 'AgeCategory', 'TetanusLast10Tdap', 'CovidPos']</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-serial"><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-18" type="checkbox"><label for="sk-estimator-id-18" class="sk-toggleable__label sk-toggleable__label-arrow">SimpleImputer</label><div class="sk-toggleable__content"><pre>SimpleImputer(strategy='most_frequent')</pre></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-19" type="checkbox"><label for="sk-estimator-id-19" class="sk-toggleable__label sk-toggleable__label-arrow">OneHotEncoder</label><div class="sk-toggleable__content"><pre>OneHotEncoder(handle_unknown='ignore')</pre></div></div></div></div></div></div></div></div></div></div><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-20" type="checkbox"><label for="sk-estimator-id-20" class="sk-toggleable__label sk-toggleable__label-arrow">LogisticRegression</label><div class="sk-toggleable__content"><pre>LogisticRegression()</pre></div></div></div></div></div></div></div></div></div></div></div></div>
</div>
</div>
<p>Finally, we can make predictions on the final model</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Cross-validated Accuracy for Logistic Regression: 0.8276561183734552</code></pre>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Through the use of our data set, we were able to accomplish the creation of a model with an accuracy of 0.8276561. This allows us to be able to make predictions on whether someone has heart disease or not. We were able to do this through the use of data visualization, data cleaning, baseline model construction, and hyperparameter tuning.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>